# Generated by Django 4.2.9 on 2024-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cart_user_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delievered', 'Delievered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
