# Generated by Django 4.2.9 on 2024-01-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orderplaced_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='razorpay_payment_signature',
        ),
    ]
