# Generated by Django 4.2.9 on 2024-01-20 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
