# Generated by Django 4.2.9 on 2024-01-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customer_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
